### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.ResolveTests_1_5` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#76] opened 2024-02-21 19:33 UTC
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by datho7561** [comment] 2024-02-21 19:46
I intend to work on this

**Comment by datho7561** [comment] 2024-02-28 20:23
The root cause of many of the failures is that resolution across compilation units doesn't seem to work. I don't yet know how to do this without resorting to the LookupEnvironment, which is linked to the compiler.

**Comment by mickaelistria** [comment] 2024-03-03 21:29
I think https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/103 will resolve most failure related to localizing other compilation units.

**Comment by mickaelistria** [comment] 2024-03-04 15:03
Some tests will be fixed with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2075 ,
Some others (test0082/test0085) seem to tell that DOMToModelPopulator is missing some infos for generic types (so could be fixed in this code.
Some others (test0070 to test0075) seem to tell that the MethodBinding.getJavaElement() fails for cases where the method is a constructor for an anonymous type. In such case, the constructor of the parent type is expected. I'm not sure if the issue is JDT failing at returning a proper value, or if we should assume JDT is correct and handle this case in CompilationUnit.resolveBinding(...).

**Comment by datho7561** [comment] 2024-03-13 13:17
Two of the remaining failures are due to a statement not being recovered by AssistParser that is recovered by SelectionParser. In order to resolve this, we should move the hack that the SelectionParser uses to recover the statement up to the AssistParser (this will involve modifying these parsers).

**Comment by mickaelistria** [comment] 2024-03-27 14:53
Remaining failures related to recovery are now ignored.

**Closed as completed by mickaelistria** 2024-03-27 14:53 UTC
Labels: dom-first
