### ISSUE TITLE
unconditional patterns in instanceof are not supported in -source 17

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#681] opened 2024-08-12 04:59 UTC
I'm trying to use javac bits to open eclipse.jdt.ls project itself, and it throws some error `unconditional patterns in instanceof are not supported in -source 17`.

![image](https://github.com/user-attachments/assets/f3ad47f5-c8ea-4388-9b7a-a82059fcd8df)

Call stack:
```
!ENTRY org.eclipse.jdt.core 4 0 2024-08-12 12:46:05.220
!MESSAGE Internal failure while parsing or converting AST for unit /org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDeclarationHandler.java

!ENTRY org.eclipse.jdt.core 4 0 2024-08-12 12:46:05.222
!MESSAGE Operation only supported in JLS21 AST
!STACK 0
java.lang.UnsupportedOperationException: Operation only supported in JLS21 AST
	at org.eclipse.jdt.core.dom.ASTNode.supportedOnlyIn21(ASTNode.java:2587)
	at org.eclipse.jdt.core.dom.Pattern.<init>(Pattern.java:42)
	at org.eclipse.jdt.core.dom.TypePattern.<init>(TypePattern.java:81)
	at org.eclipse.jdt.core.dom.AST.newTypePattern(AST.java:3340)
	at org.eclipse.jdt.core.dom.JavacConverter.convert(JavacConverter.java:1773)
	at org.eclipse.jdt.core.dom.JavacConverter.convertExpressionImpl(JavacConverter.java:1404)
	at org.eclipse.jdt.core.dom.JavacConverter.convertExpression(JavacConverter.java:1749)
	at org.eclipse.jdt.core.dom.JavacConverter.handleInfixExpression(JavacConverter.java:1665)
	at org.eclipse.jdt.core.dom.JavacConverter.convertExpressionImpl(JavacConverter.java:1321)
	at org.eclipse.jdt.core.dom.JavacConverter.convertExpression(JavacConverter.java:1749)
	at org.eclipse.jdt.core.dom.JavacConverter.convertIfStatement(JavacConverter.java:2612)
	at org.eclipse.jdt.core.dom.JavacConverter.convertStatement(JavacConverter.java:2175)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBlock(JavacConverter.java:2484)
	at org.eclipse.jdt.core.dom.JavacConverter.convertTryStatement(JavacConverter.java:2496)
	at org.eclipse.jdt.core.dom.JavacConverter.convertStatement(JavacConverter.java:2184)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBlock(JavacConverter.java:2484)
	at org.eclipse.jdt.core.dom.JavacConverter.convertMethodDecl(JavacConverter.java:894)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:696)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:557)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:486)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:699)
	at org.eclipse.jdt.core.dom.JavacConverter.lambda$populateCompilationUnit$2(JavacConverter.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.eclipse.jdt.core.dom.JavacConverter.populateCompilationUnit(JavacConverter.java:181)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:620)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:458)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1263)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1142)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5762)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1142)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:882)
	at org.eclipse.jdt.internal.core.CompilationUnit.getOrBuildAST(CompilationUnit.java:552)
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.codeSelect(DOMCodeSelector.java:107)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:526)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:518)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:1062)
	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeHover(HoverInfoProvider.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.computeHover(HoverHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:43)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:656)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:527)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
```

**Comment by testforstephen** [comment] 2024-08-13 08:27
I believe there's a discrepancy between our implementation and the upstream JDT core regarding how the AST level is set for the DOM parser.

In the upstream JDT core, when using the DOM ASTParser, the AST level is always set to IASTSharedValues.SHARED_AST_LEVEL, which corresponds to the latest Java version supported by JDT. This can be observed in typical usages of the DOM parser, such as in org.eclipse.jdt.core.manipulation.CoreASTProvider. However, in our implementation with javac, the AST level is determined based on the project's options (see org.eclipse.jdt.internal.core.CompilationUnit.getOrBuildAST). As a result, this approach causes issues when working with Java 17 projects, where the DOM parser does not function correctly.

**Comment by testforstephen** [comment] 2024-08-13 08:32
This issue can easily be reproduced when using Javac bits to work with Java 17 `instanceof` syntax.

**Comment by robstryker** [comment] 2024-08-14 14:41
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/688/commits/de6db931f2fe847d5c6088d30951f7215d1ffbfd

This commit may fix this issue. We'll see.

**Comment by fbricon** [comment] 2024-09-02 08:33
@robstryker was that commit ever merged? This issue is still present with the latest builds

**Comment by robstryker** [comment] 2024-09-16 15:26
That commit was in fact merged. If it didn't fix the issue then the issue must be deeper.

**Comment by mickaelistria** [comment] 2024-11-16 13:30
I'm seeing this issue today, but without even converting a tree. I believe the issue really comes from Javac. One thing you can try to verify this assumption is to rebuild locally with Tycho, but switching it to use javac as compiler instead of ECJ.

**Comment by mickaelistria** [comment] 2024-11-18 13:47
I can confirm that the issue can be reproduced with Javac, for example with org.eclipse.jdt.core bundle, this command shows the same error via CLI (and disappears when release is set to 21)
```
javac -implicit:none --source-path /home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/codeassist:/home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/dom:/home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/eval:/home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/formatter:/home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/model:/home/mistria/runtime-IDEwithJavac/eclipse.jdt.core/org.eclipse.jdt.core/search --class-path /usr/lib/jvm/java-23-openjdk-23.0.1.0.11-1.rolling.fc41.x86_64/lib/jrt-fs.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.core.resources_3.22.0.v20241001-1711.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.core.runtime_3.32.0.v20241003-0436.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.osgi_3.22.0.v20241030-2121.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.osgi.compatibility.state_1.2.1000.v20240213-1057.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.equinox.common_3.19.200.v20241004-0654.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.core.jobs_3.15.400.v20240619-0602.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.equinox.registry_3.12.200.v20241004-0654.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.equinox.preferences_3.11.200.v20240911-1044.jar:/home/mistria/apps/eclipse-SDK/plugins/org.osgi.service.prefs_1.1.2.202109301733.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.core.contenttype_3.9.600.v20241001-1711.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.equinox.app_1.7.200.v20240722-2103.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.core.filesystem_1.11.100.v20241022-0806.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.text_3.14.200.v20240915-0736.jar:/home/mistria/apps/eclipse-SDK/plugins/org.eclipse.team.core_3.10.500.v20240621-0541.jar:/home/mistria/git/eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/bin:/home/mistria/apps/eclipse-SDK/plugins/org.apache.ant_1.10.15.v20240901-1000/lib/ant.jar --release 17 codeassist/org/eclipse/jdt/internal/codeassist/complete/CompletionParser.java -d ~/sandbox
```
So it just looks like a feature where ECJ is more tolerant than Java.

**Closed as completed by mickaelistria** 2024-11-18 13:47 UTC
Labels: bug, javac
