### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.TypeResolveTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#82] opened 2024-02-21 19:39 UTC
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment] 2024-03-11 15:18
Some tests are failing because it looks like the expectation is that types should be added as children of other types only, not as children of a method or a field (as we're doing right now), the "addAsChild" method can be improved on that aspect.

Another family of issue is that the most complex types are not resolved by the SearchEngine. It looks like we need to "explode" the type into more atomic one and aggregate the result for each atom.

**Comment by mickaelistria** [comment] 2024-03-12 10:48
testBug576778 is caused by upstream issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2142

**Comment by mickaelistria** [comment] 2024-04-08 13:55
All fixed now

**Closed as completed by mickaelistria** 2024-04-08 13:55 UTC
Labels: dom-first
